Add ability to spoof media-layer frames
OpenCyphal/pycyphal pull request #260
Opened 2022-11-18 17:32 UTC by silverv

2022-11-18 17:33 UTC, pavel-kirienko requested changes
Unit tests are missing.

2022-11-21 17:29 UTC, pavel-kirienko commented on pycyphal/transport/can/_can.py
> +                monotonic_deadline=asyncio.get_running_loop().time() + 1.0,
Do we not want to expose the transmission deadline as an argument for this method? I think it would make the logic in Yukon more explicit.

2022-11-21 17:30 UTC, pavel-kirienko commented on setup.cfg
> +
uh oh

2022-11-21 17:32 UTC, pavel-kirienko commented on tests/transport/can/_can.py
> +    all_media1_received_event = asyncio.Event()
The media1 reception pipeline is not used anywhere and should be removed.

2022-11-23 20:12 UTC, silverv commented
I have since gotten distracted with fixing Pycyphal itself and I should come back to the real issue that this pull request is actually done and we should merge it.

2022-11-23 20:13 UTC, silverv commented
But that comes after I revert all the fixes that didn't manage to fix Pycyphal and didn't manage to make the life of a developer easier.

2022-11-30 16:49 UTC, pavel-kirienko commented
The MyPy problem was caused by a regression in it: https://github.com/python/mypy/issues/13627. I fixed it by upgrading to the latest MyPy; this necessitated some minor additional changes throughout (see the latest commit).

There was a type error and two logical errors in spoof_frames which I fixed. The unit test needs to be updated per my request above and also the `own` flag needs to be checked in the test.

2022-12-08 17:49 UTC, pavel-kirienko approved these changes

2022-12-08 19:57 UTC, merged