Migrate to Nunavut v2
OpenCyphal/pycyphal pull request #318
Opened 2024-01-03 04:46 UTC by Willmac16

Addresses #277 

I'm still a bit unsure about how I'm handling `nunavut_support.py`, so I'd appreciate feedback on that and anything else.

2024-01-03 11:47 UTC, pavel-kirienko requested changes
Please run Black to fix code formatting.

Also do not forget to bump the minor version when the PR is ready.

2024-01-03 11:47 UTC, pavel-kirienko commented on setup.cfg
> +    nunavut >= 2.0
```suggestion
    nunavut ~= 2.3
```

2024-01-03 11:47 UTC, pavel-kirienko commented on tests/dsdl/_builtin_form.py
This test is no longer needed here as it has been migrated to Nunavut.

2024-01-03 11:47 UTC, pavel-kirienko commented on tests/dsdl/_constants.py
This test is no longer needed here as it has been migrated to Nunavut.

2024-01-03 11:47 UTC, pavel-kirienko commented on tests/dsdl/_manual.py
This test is no longer needed here as it has been migrated to Nunavut.

2024-01-03 11:47 UTC, pavel-kirienko commented on tests/dsdl/_rand.py
This test is no longer needed here as it has been migrated to Nunavut.

2024-01-03 11:47 UTC, pavel-kirienko commented on tests/dsdl/_textual.py
This test is no longer needed here as it has been migrated to Nunavut.

2024-01-03 11:47 UTC, pavel-kirienko commented on pycyphal/dsdl/_compiler.py
>      this submodule provides helper functions
```suggestion
    its name is a reserved identifier or not (i.e., whether it's stropped or not). To simplify usage,
    the Nunavut-generated module ``nunavut_support.py`` provides helper functions
```

2024-01-04 02:00 UTC, Willmac16 commented
It looks like Yakut needs the `pycyphal.dsdl.([a-z_]+)` -> `nunavut_support.$1` treatment.

2024-01-04 08:59 UTC, pavel-kirienko commented
>Unrelated, should the package be marked as `zip_safe` in setup.cfg at this point?

Maybe, but it would probably be a micro-optimization and this flag is obsolete either way, so I prefer not to touch it. See https://setuptools.pypa.io/en/latest/deprecated/zip_safe.html

2024-01-04 09:05 UTC, pavel-kirienko commented
>It looks like Yakut needs the pycyphal.dsdl.([a-z_]+) -> nunavut_support.$1 treatment.

I have opened a ticket about this in the Yakut repo. Would you be available to submit the required changes there? For testing, you can replace the PyCyphal dependency specification as follows:

```diff
 install_requires =
-    pycyphal[transport-udp,transport-serial,transport-can-pythoncan] ~= 1.8
+    pycyphal[transport-udp,transport-serial,transport-can-pythoncan] ~= git+https://github.com/Willmac16/pycyphal@Willmac16/issue277
```

You can temporarily replace the Yakut dependency in PyCyphal integration tests in a similar fashion.

2024-01-04 09:48 UTC, pavel-kirienko requested changes
>>It looks like Yakut needs the pycyphal.dsdl.([a-z_]+) -> nunavut_support.$1 treatment.
>
>I have opened a ticket about this in the Yakut repo.

Wait, I have a better idea. Can we please provide wrappers in `pycyphal.dsdl` (perhaps right in `__init__.py`, for simplicity) of the form:

```python
def update_from_builtin(destination: T, source: Any) -> T:
    """
    A wrapper over ``nunavut_support.update_from_builtin``.
    The ``nunavut_support`` module will be generated automatically if it is not importable.
    """
    from nunavut_support import update_from_builtin

    return update_from_builtin(destination, source)
```

That should avoid the breakage of Yakut.

-----

Also, could you please update the docs here:

- https://pycyphal--318.org.readthedocs.build/en/318/pages/architecture.html#dsdl-support
- https://pycyphal--318.org.readthedocs.build/en/318/api/pycyphal.dsdl.html#module-pycyphal.dsdl

`CompositeObject` and `ServiceObject` are simply gone now.

2024-01-04 09:48 UTC, pavel-kirienko commented on pycyphal/application/_port_list_publisher.py
> +import pycyphal.dsdl
This import doesn't seem to be necessary.

2024-01-04 09:48 UTC, pavel-kirienko commented on tests/presentation/_pub_sub.py
> +import nunavut_support
Please move this import into the function scope.

2024-01-04 09:48 UTC, pavel-kirienko commented on tests/presentation/subscription_synchronizer/transfer_id.py
> +import nunavut_support
Please move this import into the function scope.

2024-01-04 20:35 UTC, Willmac16 commented
Once everything in this PR is good to go 🤞 

Can I squash my commits into one to keep the commit history of upstream clean.

2024-01-05 11:24 UTC, pavel-kirienko requested changes
I think it looks good aside from a few minor nits. Please request another review when done and we'll have it merged.

2024-01-05 11:24 UTC, pavel-kirienko commented on docs/pages/architecture.rst
> +  These functions are wrappers of the Nunavut generated support functions in `nunavut_support.py`.
This applies to `serialize`/`deserialize` as well.

2024-01-05 11:24 UTC, pavel-kirienko commented on pycyphal/dsdl/_compiler.py
> +        If set to None, only nunavut_support will be generated
```suggestion
        If set to None, only the ``nunavut_support`` module will be generated.
```

2024-01-05 11:24 UTC, pavel-kirienko commented on pycyphal/dsdl/__init__.py
> +T = TypeVar("T")
This should be either prefixed with an underscore or moved into a separate module to prevent scope leakage.

2024-01-08 18:37 UTC, pavel-kirienko approved these changes

2024-01-08 18:51 UTC, merged