Improve demo documentation
OpenCyphal/pycyphal pull request #319
Opened 2024-01-03 10:22 UTC by maksimdrachov

2024-01-03 10:51 UTC, pavel-kirienko requested changes
See comrade, `yakut compile` is not needed anymore. `YAKUT_PATH` went the same way. The command itself will be removed from Yakut during the next sprint. All you need to do is set `CYPHAL_PATH` pointing to where your DSDL root directories are, and compilation will happen automatically as needed. You will update the docs accordingly yes?

2024-01-03 10:57 UTC, maksimdrachov commented
> next sprint

so, give or take, somewhere in the next decade?

2024-01-03 11:06 UTC, pavel-kirienko commented
My bad, I meant the next five-year plan, aka *pyatiletka*.

2024-01-10 16:28 UTC, pavel-kirienko approved these changes

2024-01-10 20:50 UTC, merged